[project]
name = "black-gate"

[paths]
data = "game-data"
work = "remaster_data"

[render]
scale = 6
logical_width = 320
logical_height = 200

[gpu]
devices = ["cuda:1"]
workers = 1
precision = "fp16"
