"""Arcadion speaker-attribution curation table.

Auto-derived from bilingual_mapping_review.json on 2026-08-23 alongside the
reviewed curation (see fix_arcadion_attribution.py). Each entry:
  (en_func_id, en_offset_key, en_segment, target_npc,
   expected_current_npc, expected_en_text_prefix)
The prefix guards against silent drift: if the text at a runtime key ever
changes, the patch refuses to reassign rather than misattribute.
"""

TABLE = [
    ("0x06F6", "0", 0, "Arcadion", "UNKNOWN",
     "\"Yes, Master. How may I serve you?\" The dark form in the mirror bows d"),
    ("0x06F6", "10c", 0, "Arcadion", "UNKNOWN",
     "Through a tightly clenched smile, the figure replies, \"Very well...\" A"),
    ("0x06F6", "17b", 0, "Arcadion", "UNKNOWN",
     "Arcadion appears truly astonished, \"For what do you wait?! I beg of yo"),
    ("0x06F6", "1d5", 0, "Arcadion", "UNKNOWN",
     "\"There is a gem nearby that can free me! It is a small blue stone. Tak"),
    ("0x06F6", "28e", 0, "Arcadion", "UNKNOWN",
     "\"Can I be of some small assistance in your quest to release me. If so,"),
    ("0x06F6", "32c", 0, "Arcadion", "UNKNOWN",
     "\"you have within your possessions a small blue gem. It can be used to "),
    ("0x06F6", "48e", 0, "Arcadion", "UNKNOWN",
     "\"Run along now little mortal. Do not pester your betters with the idle"),
    ("0x06F6", "572", 0, "Arcadion", "UNKNOWN",
     "A wicked look of triumph flickers across Arcadion's face to be quickly"),
    ("0x06F6", "6f5", 0, "Arcadion", "UNKNOWN",
     "\"Ah, I see. Still content to run about with the other sheep.\" He waves"),
    ("0x06F6", "75a", 0, "Arcadion", "UNKNOWN",
     "\"Yes, Master. How may I serve you...\" The wavering visage in the mirro"),
    ("0x06F6", "7d5", 0, "Arcadion", "UNKNOWN",
     "He then continues with a small bow, \"Greetings Britannian. What do you"),
    ("0x06F6", "858", 0, "Arcadion", "UNKNOWN",
     "\"Greetings once again Britannian. What do you wish of me.\" The daemon "),
    ("0x06F6", "8d7", 0, "Arcadion", "UNKNOWN",
     "The big daemon smiles ingratiatingly, showing inch long pointed teeth."),
    ("0x06F6", "94a", 0, "Arcadion", "UNKNOWN",
     "His somewhat polished veneer seems to be unravelling at the edges in h"),
    ("0x06F6", "9bc", 0, "Arcadion", "UNKNOWN",
     "Arcadion attempts to smile, but failing miserably, he gives you a grim"),
    ("0x06F6", "afe", 0, "Arcadion", "UNKNOWN",
     "\"Well, if you keepest your promise to release me, I'll be free of that"),
    ("0x06F6", "b7f", 0, "Arcadion", "UNKNOWN",
     "\"He is my master...\" The daemon's smile contorts into a scarcely hidde"),
    ("0x06F6", "c56", 0, "Arcadion", "UNKNOWN",
     "\"That is how your people address those of my race.\" You can't tell fro"),
    ("0x06F6", "ce6", 0, "Arcadion", "UNKNOWN",
     "The large daemon's eyes close as he appears to be restraining the forc"),
    ("0x06F6", "d44", 0, "Arcadion", "UNKNOWN",
     "\"I have served that blind, old fool for over two hundred years!\" Arcad"),
    ("0x06F6", "101a", 0, "Arcadion", "UNKNOWN",
     "Arcadion looks as if he's about to force his way through the mirror, t"),
    ("0x06F6", "108c", 0, "Arcadion", "UNKNOWN",
     "He folds massive arms across a broad chest and slowly restores his gru"),
    ("0x06F6", "11c5", 0, "Arcadion", "UNKNOWN",
     "\"I'll need a special gem in which to house my essence when you crackes"),
    ("0x06F6", "127b", 0, "Arcadion", "UNKNOWN",
     "\"I can sense that the gem is near! Take it! Take it, quickly and use i"),
    ("0x06F6", "1316", 0, "Arcadion", "UNKNOWN",
     "\"There was one on this island, that much I know. Find it. Bring it to "),
    ("0x06F6", "13ae", 0, "Arcadion", "UNKNOWN",
     "\"you have the gem! I feel it! Use it now to crack the mirror! I'll ent"),
    ("0x06F6", "14d2", 0, "Arcadion", "UNKNOWN",
     "Arcadion winks in a very undaemonlike manner, \"Farewell, brave mortal."),
    ("0x06F6", "1544", 0, "Arcadion", "UNKNOWN",
     "The smiling daemon bows again, \"Fare you well, Britannian. Until we me"),
    ("0x06F6", "3f0", 0, "Arcadion", "UNKNOWN",
     "\"Can I be of some small assistance in your quest to release me. If so,"),
    ("0x06F6", "e9e", 0, "Arcadion", "UNKNOWN",
     "A wicked look of triumph flickers across Arcadion's face to be quickly"),
    ("0x06F6", "1436", 0, "Arcadion", "UNKNOWN",
     "\"There was one on this island, that much I know. Find it. Bring it to "),
    ("0x06F6", "15d4", 0, "Arcadion", "Hook",
     "The little gem pulses with energy, \"Now all Britannia shall feel my wr"),
    ("0x06F6", "17b4", 0, "Arcadion", "Hook",
     "The gem sparkles up at you, \"Yes, master. How may I serve you?\" Arcadi"),
    ("0x06F6", "1844", 0, "Arcadion", "Hook",
     "\"If you do wish me to bond the gem to the sword, you have but to comma"),
    ("0x06F6", "18b4", 0, "Arcadion", "Hook",
     "\"It will be done!\""),
    ("0x06F6", "1a42", 0, "Arcadion", "Hook",
     "\"The sword and gem must be in your hands for the bonding to be accompl"),
    ("0x06F6", "1a99", 0, "Arcadion", "Hook",
     "\"My name is still Arcadion, although my prison has changed.\""),
    ("0x06F6", "1adf", 0, "Arcadion", "Hook",
     "\"I am now your servant. What is your bidding, master?\""),
    ("0x06F6", "1b25", 0, "Arcadion", "Hook",
     "Arcadion sounds a bit pensive as he replies, \"Forgive my momentary ind"),
    ("0x06F6", "1c0b_1c20", 0, "Arcadion", "Hook",
     "\"It would seem that the mage Erethian was correct in his assumption th"),
    ("0x06F6", "1ce8", 0, "Arcadion", "Hook",
     "You hear a faint sigh, then, \"would you care to partake of my power?\""),
    ("0x06F6", "1d31", 0, "Arcadion", "Hook",
     "Arcadion sounds disappointed, \"It is as I knew it would be. I am forev"),
    ("0x06F6", "1df8", 0, "Arcadion", "Hook",
     "\"Perhaps I misjudged you, master.\" He pauses for a thoughtful moment, "),
    ("0x06F6", "1e89", 0, "Arcadion", "Hook",
     "\"you have need of my energies again?\" Arcadion asks a little petulantl"),
    ("0x06F6", "1ed3", 0, "Arcadion", "Hook",
     "\"Very well, prepare yourself.\" The gem glows."),
    ("0x06F6", "1f07", 0, "Arcadion", "Hook",
     "\"What do you seek of me...\" A pause, \"Master?\""),
    ("0x06F6", "1f40", 0, "Arcadion", "Hook",
     "\"do you seek to torment me with useless questions, or may I be of some"),
    ("0x06F6", "1fc2", 0, "Arcadion", "Hook",
     "The daemon pauses for a moment, \"you have imprisoned my physical form,"),
    ("0x06F6", "2087", 0, "Arcadion", "Hook",
     "\"Long ago, even by my accounting of time, my people were defeated by a"),
    ("0x06F6", "22f0", 0, "Arcadion", "Hook",
     "\"Farewell my master.\" The gem seems to dim a little."),
    ("0x06F6", "18c7", 0, "UNKNOWN", "Hook",
     "As the gem touches the crosspiece of the sword, the sound of tearing m"),
    ("0x06F6", "195f", 0, "UNKNOWN", "Hook",
     "Slowly, the sword settles into its original shape, except for the blue"),
    ("0x06F6", "19bf", 0, "UNKNOWN", "Hook",
     "There is a flash of what can only be described as black light and the "),
    ("0x06F6", "2326", 0, "Arcadion", "Dark Core",
     "The sword glimmers darkly as you speak to it. \"Greetings, my master. A"),
    ("0x06F6", "23d9", 0, "Arcadion", "Dark Core",
     "\"Yes, master. What do you seek of your servant?\" Arcadion asks you in "),
    ("0x06F6", "2457", 0, "Arcadion", "Dark Core",
     "The daemon sword's tone is rather ominous as he says, \"I am, and ever "),
    ("0x06F6", "24c7", 0, "Arcadion", "Dark Core",
     "\"I am the Shade Blade. My destiny is to serve you until we are...\" The"),
    ("0x06F6", "2532", 0, "Arcadion", "Dark Core",
     "\"I needs must be in your hand, master, if you wishest to use my powers"),
    ("0x06F6", "257b", 0, "Arcadion", "Dark Core",
     "\"Which of my powers do you seek to use?\""),
    ("0x06F6", "25c9", 0, "Arcadion", "Dark Core",
     "Arcadion's voice is smug as he replies to your request for assistance."),
    ("0x06F6", "2790", 0, "Arcadion", "Dark Core",
     "\"The concave and convex lenses which you used to place the Codex of In"),
    ("0x06F6", "2899", 0, "Arcadion", "Dark Core",
     "\"The Talismans of Principle must be placed upon the Dark Core like wed"),
    ("0x06F6", "28fd", 0, "Arcadion", "Dark Core",
     "\"As you wish, master. I but seek to serve you.\""),
    ("0x06F6", "2935", 0, "Arcadion", "Dark Core",
     "The blade croons quietly, \"Alas, master. My energies seem a trifle low"),
    ("0x06F6", "2a01", 0, "Arcadion", "Dark Core",
     "\"Where is the corpse of which you do speak?\" The dark sword begins to "),
    ("0x06F6", "2a61", 0, "Arcadion", "Dark Core",
     "The daemon speaks with a sanctimonious tone. \"I could not in honor tak"),
    ("0x06F6", "2acf", 0, "Arcadion", "Dark Core",
     "\"Yes! I have long sought the end of Lord British, my traitorous master"),
    ("0x06F6", "2ff6", 0, "Arcadion", "Dark Core",
     "The daemon, possibly stung by the dragon's repartee, falls silent and "),
    ("0x06F6", "3056", 0, "Arcadion", "Dark Core",
     "The Shade Blade croons sofltly. \"Move a little closer to the dragon, a"),
    ("0x06F6", "30c4", 0, "Arcadion", "Dark Core",
     "\"I owe you quite a favor for this, master. I thank you for allowing me"),
    ("0x06F6", "3121", 0, "Arcadion", "Dark Core",
     "\"Move closer to him, and I'll see that his life plagues you no more.\" "),
    ("0x06F6", "319f", 0, "Arcadion", "Dark Core",
     "\"This creature is not strictly speaking,... living. your best course o"),
    ("0x06F6", "3233", 0, "Arcadion", "Dark Core",
     "\"Very well, master. If you cannot dispatch this foe yourself, I shall "),
    ("0x06F6", "328a", 0, "Arcadion", "Dark Core",
     "\"I must get closer to this one in order to enjoy its essence.\" The bla"),
    ("0x06F6", "3315", 0, "Arcadion", "Dark Core",
     "The daemon sword abruptly ceases its vibration. \"This being is hardly "),
    ("0x06F6", "33d8", 0, "Arcadion", "Dark Core",
     "\"Perhaps you misunderstands my meaning. I do not raise the dead... I s"),
    ("0x06F6", "345a", 0, "Arcadion", "Dark Core",
     "\"you would have me destroy the very world around you. Not a very brigh"),
    ("0x06F6", "3514", 0, "Arcadion", "Dark Core",
     "The sword recoils in something akin to horror. \"That one is beyond eve"),
    ("0x06F6", "362a", 0, "Arcadion", "Dark Core",
     "\"you shall not be rid of me quite so easily, my master. However, I do "),
    ("0x06F6", "36c4", 0, "Arcadion", "Dark Core",
     "\"Would that I had such power. That artifact would allow me to return t"),
    ("0x06F6", "373f", 0, "Arcadion", "Dark Core",
     "\"have you such a grudge against this inanimate object that you would s"),
    ("0x06F6", "380e", 0, "Arcadion", "Dark Core",
     "\"Ah... home again. I never tire of rocky little islands. do you truly "),
    ("0x06F6", "3881", 0, "Arcadion", "Dark Core",
     "\"I see. Very well, master. But let us not forget this little favor...\""),
    ("0x06F6", "390f", 0, "Arcadion", "Dark Core",
     "\"It is good. Sense returns to the Virtuous Wonder. you are truly witho"),
    ("0x06F6", "3980", 0, "Arcadion", "Dark Core",
     "\"Forgive me, master, but are we not already on or near the Isle of Fir"),
    ("0x06F6", "3a29", 0, "Arcadion", "Dark Core",
     "\"And what, pray tell, is the intended target of your immense and most "),
    ("0x06F6", "3aa6", 0, "Arcadion", "Dark Core",
     "\"Forgive me master, but I shan't be leaving. However, you may cease yo"),
    ("0x06F6", "3567", 0, "Arcadion", "Dark Core",
     "The daemon sword abruptly ceases its vibration. \"This being is hardly "),
    ("0x06F6", "2cf9", 0, "Arcadion", "Lord British",
     "The Shade Blade lets out a harsh whisper. \"Move a little closer to him"),
    ("0x06F6", "2d6f", 0, "Arcadion", "Lord British",
     "\"Alas master, this one is protected by a power greater than mine. His "),
    ("0x06F6", "2dce", 0, "Arcadion", "Lord British",
     "The sword recoils in something akin to horror. \"That creature is beyon"),
    ("0x06F6", "2e8c", 0, "Arcadion", "Lord British",
     "\"Ah, Dracothraxus. We meet once again. It is a pity you shan't survive"),
    ("0x06F6", "2b63", 0, "Arcadion", "Avatar",
     "The daemon responds, using your mouth. \"This blade is your doom,...\" Y"),
    ("0x06F6", "2f59", 0, "Arcadion", "Dracothraxus",
     "The dragon responds with great resignation. \"My will is not mine own i"),
    ("0x009A", "b94", 0, "Arcadion", "Erethian",
     "Arcadion's voice whispers to you like ripple in still pond, \"Fear not,"),
    ("0x009A", "10a2", 0, "Arcadion", "Erethian",
     "Arcadion's voice whispers to you like ripple in still pond, \"Fear not,"),
    # Forge of Virtue ceremony scene (func 0x0608): the disassembler's old face
    # collision attributed these two rows to speaker=Arcadion in the source CSVs;
    # they belong to the Fellowship ceremony (canonical mapping npc: Batlin).
    # Targets keep the status-quo attribution so Phase C stops grouping them
    # under Arcadion.
    ("0x0608", "1a1", 0, "Batlin", "Batlin",
     "Hook points to you."),
    ("0x0608", "1b5_1d0_1e4", 0, "Batlin", "Batlin",
     "\"I say -kill- the Avatar! he is dangerous! Cut him throat! I say we at"),
]

