#!/usr/bin/env python3
"""
Rename or copy English .ogg voice files to Chinese filenames using a
mapping CSV generated by generate_offset_mapping.py.

Usage:
    # Preview
    python remap_voice_files.py
        --mapping offset_mapping.csv
        --audio-dir <PATCH>/voice_acting
        --dry-run

    # Copy (safe — preserves originals)
    python remap_voice_files.py
        --mapping offset_mapping.csv
        --audio-dir <PATCH>/voice_acting
        --mode copy

    # Rename (destructive — originals are renamed)
    python remap_voice_files.py
        --mapping offset_mapping.csv
        --audio-dir <PATCH>/voice_acting
        --mode rename
"""

import argparse
import csv
import os
import shutil
import sys


def build_source_path(audio_dir, func_id, offset_key, segment):
    """Build the expected source filename (English naming)."""
    fid = func_id.lower().replace('0x', '')
    base = f"{fid}_{offset_key}_{segment}"
    return os.path.join(audio_dir, f"{base}.ogg")


def build_target_path(audio_dir, func_id, offset_key, segment):
    """Build the expected target filename (Chinese naming)."""
    fid = func_id.lower().replace('0x', '')
    base = f"{fid}_{offset_key}_{segment}"
    return os.path.join(audio_dir, f"{base}.ogg")


def main():
    parser = argparse.ArgumentParser(
        description="Remap voice .ogg files from English to Chinese offset keys")
    parser.add_argument('--mapping', '-m', required=True,
                        help='Mapping CSV from generate_offset_mapping.py')
    parser.add_argument('--audio-dir', '-d', required=True,
                        help='Directory containing .ogg files')
    parser.add_argument('--mode', choices=['copy', 'rename'], default='copy',
                        help="'copy' preserves originals (default), 'rename' is destructive")
    parser.add_argument('--dry-run', '-n', action='store_true',
                        help='Preview without modifying files')
    parser.add_argument('--force', '-f', action='store_true',
                        help='Overwrite existing target files')
    args = parser.parse_args()

    audio_dir = args.audio_dir
    if not os.path.isdir(audio_dir):
        print(f"Error: audio directory not found: {audio_dir}", file=sys.stderr)
        sys.exit(1)

    # Read mapping
    mappings = []
    with open(args.mapping, newline='', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            mappings.append(row)

    if not mappings:
        print("Error: no mappings found", file=sys.stderr)
        sys.exit(1)

    stats = {'copied': 0, 'renamed': 0, 'skipped_source_missing': 0,
             'skipped_target_exists': 0, 'errors': 0}

    for m in mappings:
        en_key = m['en_offset_key']
        en_seg = m['en_segment']
        zh_key = m['zh_offset_key']
        zh_seg = m['zh_segment']
        fid = m['en_func_id']  # same as zh_func_id

        src_path = build_source_path(audio_dir, fid, en_key, int(en_seg))
        dst_name = os.path.basename(build_target_path(audio_dir, fid, zh_key, int(zh_seg)))
        dst_path = os.path.join(audio_dir, dst_name)

        if not os.path.exists(src_path):
            stats['skipped_source_missing'] += 1
            if args.dry_run:
                print(f"  [MISSING] {src_path}")
            continue

        if os.path.exists(dst_path) and args.mode == 'copy' and not args.force:
            stats['skipped_target_exists'] += 1
            if args.dry_run:
                print(f"  [EXISTS]  {dst_name}")
            continue

        if args.dry_run:
            if args.mode == 'copy':
                print(f"  [COPY]    {os.path.basename(src_path)} -> {dst_name}")
            else:
                print(f"  [RENAME]  {os.path.basename(src_path)} -> {dst_name}")
            continue

        try:
            if args.mode == 'copy':
                shutil.copy2(src_path, dst_path)
                stats['copied'] += 1
                print(f"  Copied: {os.path.basename(src_path)} -> {dst_name}")
            else:
                os.rename(src_path, dst_path)
                stats['renamed'] += 1
                print(f"  Renamed: {os.path.basename(src_path)} -> {dst_name}")
        except Exception as e:
            stats['errors'] += 1
            print(f"  ERROR: {e}", file=sys.stderr)

    # Summary
    print(f"\n{'=' * 50}")
    if args.dry_run:
        mode_str = f"DRY RUN ({args.mode})"
        mode_str += " [FORCE]" if args.force else ""
        print(f"{mode_str}:")
    else:
        mode_str = f"SUMMARY ({args.mode})"
        mode_str += " [FORCE]" if args.force else ""
        print(f"{mode_str}:")
    print(f"  Mappings processed: {len(mappings)}")
    if args.mode == 'copy':
        print(f"  Copied: {stats['copied']}")
    else:
        print(f"  Renamed: {stats['renamed']}")
    print(f"  Skipped (source missing): {stats['skipped_source_missing']}")
    print(f"  Skipped (target exists): {stats['skipped_target_exists']}")
    if stats['errors']:
        print(f"  Errors: {stats['errors']}")


if __name__ == '__main__':
    main()
