name: ci-macos

on:
  push:
    paths:
      - "**"
      - "!android/**"
      - "!docs/**"
      - "docs/Makefile.am"
      - "!ios/**"
      - "!msvcstuff/**"
      - "!win32/**"
      - "!AUTHORS"
      - "!ChangeLog"
      - "!COPYING"
      - "!FAQ"
      - "!INSTALL"
      - "!NEWS"
      - "!**README**"
      - "!**.ico"
      - "!**.md"
      - "!**.png"
      - "!**.txt"
      - "!.clang*"
      - "!.gitignore"
      - "!.gitattributes"
      - "!.github/workflows/*"
      - ".github/workflows/ci-macos.yml"
  pull_request:
    paths:
      - "**"
      - "!android/**"
      - "!docs/**"
      - "docs/Makefile.am"
      - "!ios/**"
      - "!msvcstuff/**"
      - "!win32/**"
      - "!AUTHORS"
      - "!ChangeLog"
      - "!COPYING"
      - "!FAQ"
      - "!INSTALL"
      - "!NEWS"
      - "!**README**"
      - "!**.ico"
      - "!**.md"
      - "!**.png"
      - "!**.txt"
      - "!.clang*"
      - "!.gitignore"
      - "!.gitattributes"
      - "!.github/workflows/*"
      - ".github/workflows/ci-macos.yml"

jobs:
  ci-macos:
    runs-on: macos-latest
    steps:
      - name: Install Intel Homebrew and dependencies
        run: |
          echo "Installing Intel Homebrew via Rosetta 2..."
          arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          IBREW="/usr/local/bin/brew"
          $IBREW update
          $IBREW install automake libtool pkg-config libpng libogg libvorbis fluid-synth freetype gtk+3 libxml2 bison flex sdl3 sdl3_image icu4c mt32emu autoconf-archive dylibbundler create-dmg
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Run autoreconf
        run: |
          autoreconf -v -i
      - name: Configure
        run: |
          export MACOSX_DEPLOYMENT_TARGET="11.0"
          export CFLAGS="-arch x86_64"
          export CXXFLAGS="-arch x86_64"
          export OBJCFLAGS="-arch x86_64"
          export OBJCXXFLAGS="-arch x86_64"
          IBREW="/usr/local/bin/brew"
          export LDFLAGS="-arch x86_64 -Wl,-headerpad_max_install_names -L$($IBREW --prefix bison)/lib -L$($IBREW --prefix flex)/lib -L$($IBREW --prefix freetype)/lib"
          export CPPFLAGS="-I$($IBREW --prefix flex)/include -I$($IBREW --prefix freetype)/include/freetype2"
          export PATH="$($IBREW --prefix bison)/bin:$($IBREW --prefix flex)/bin:$($IBREW --prefix libxml2)/bin:/usr/local/bin:$PATH"
          export PKG_CONFIG_PATH="$($IBREW --prefix libxml2)/lib/pkgconfig:$($IBREW --prefix icu4c)/lib/pkgconfig:$($IBREW --prefix freetype)/lib/pkgconfig"
          export LIBS="-lfreetype"
          ./configure --host=x86_64-apple-darwin --with-debug=extreme --enable-exult-studio --enable-exult-studio-support --enable-compiler \
            --enable-zip-support --enable-shared --enable-shp-thumbnailer --enable-data --enable-mods --enable-aseprite-plugin \
            --disable-alsa --disable-timidity-midi
      - name: Build
        run: |
          export MACOSX_DEPLOYMENT_TARGET="11.0"
          export CFLAGS="-arch x86_64"
          export CXXFLAGS="-arch x86_64"
          export OBJCFLAGS="-arch x86_64"
          export OBJCXXFLAGS="-arch x86_64"
          IBREW="/usr/local/bin/brew"
          export LDFLAGS="-arch x86_64 -Wl,-headerpad_max_install_names -L$($IBREW --prefix bison)/lib -L$($IBREW --prefix flex)/lib -L$($IBREW --prefix freetype)/lib"
          export CPPFLAGS="-I$($IBREW --prefix flex)/include -I$($IBREW --prefix freetype)/include/freetype2"
          export PATH="$($IBREW --prefix bison)/bin:$($IBREW --prefix flex)/bin:$($IBREW --prefix libxml2)/bin:/usr/local/bin:$PATH"
          export PKG_CONFIG_PATH="$($IBREW --prefix libxml2)/lib/pkgconfig:$($IBREW --prefix icu4c)/lib/pkgconfig:$($IBREW --prefix freetype)/lib/pkgconfig"
          export LIBS="-lfreetype"
          make -j3
          make osxdmg
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Exult-macOS-Build
          path: Exult*.dmg
  notify:
    if: ${{ always() }}
    needs:
      - ci-macos
    uses: ./.github/workflows/notify.yml
    with:
      build_name: "The Exult macOS build"
      build_result: ${{ needs.ci-macos.result }}
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
